name = "fitbit2garmin"
pages_build_output_dir = "frontend/dist"
compatibility_date = "2023-12-01"
compatibility_flags = ["nodejs_compat"]

[vars]
ENVIRONMENT = "production"

[[kv_namespaces]]
binding = "RATE_LIMITS"
id = "cdaa358255684b39b8f9429dab347cec"

[[r2_buckets]]
binding = "FILE_STORAGE"
bucket_name = "fitbit2garmin-files"
