name = "fitbit2garmin-api"
main = "src/worker.js"
compatibility_date = "2023-12-01"

[vars]
ENVIRONMENT = "production"

[[kv_namespaces]]
binding = "RATE_LIMITS"
id = "cdaa358255684b39b8f9429dab347cec"

[build]
command = "npm run build"
cwd = "."