name = "fitbit2garmin"
pages_build_output_dir = "frontend/dist"
compatibility_date = "2023-12-01"

[vars]
ENVIRONMENT = "production"

[[kv_namespaces]]
binding = "RATE_LIMITS"
id = "cdaa358255684b39b8f9429dab347cec"